DOS_PPE/Controllers/DashboardController.cs
using DOS_PPE.Data;
using Microsoft.AspNetCore.Mvc;
using Rental.Controllers;

namespace DOS_PPE.Controllers
{
    public class DashboardController : BaseController
    {
        private readonly ApplicationDBContext _contextemp;
        private readonly SecondDbContext _context;

        public DashboardController(ApplicationDBContext contextemp, SecondDbContext context) : base(contextemp, context)
        {
            _context = context;
            _contextemp = contextemp;
        }

        public IActionResult Dashboard()
        {
            if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

            return View();
        }

        public IActionResult Index_Approval()
        {
            if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

            return View();
        }

        public IActionResult Goods_Receipt()
        {
            if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

            return View();
        }
    }
}

DOS_PPE/Controllers/PermissionController.cs
using DOS_PPE.Data;
using DOS_PPE.Models;
using Microsoft.AspNetCore.Mvc;
using Rental.Controllers;
using System.Xml.Linq;

namespace DOS_PPE.Controllers
{
    public class PermissionController : BaseController
    {
        private readonly ApplicationDBContext _contextemp;
        private readonly SecondDbContext _context;

        public PermissionController(ApplicationDBContext contextemp, SecondDbContext context) : base(contextemp, context)
        {
            _context = context;
            _contextemp = contextemp;
        }

        public IActionResult Permission()
        {
            if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

            //List modal add member
            var QSMS = _contextemp.Employee.Where(q => q.department == "QSMS" && q.status_active == "on").ToList();

            //Table show data permission
            var permissions = _context.Permission.ToList();
            var employees = _contextemp.Employee.Where(q => q.status_active == "on").ToList();
            var Permis = (from perm in permissions
                          join emp in employees on perm.employee_id equals emp.employee_id
                          where(emp.employee_id == perm.employee_id)
                          select new ApermisModel
                          {
                              employee_id = perm.employee_id,
                              name_en = emp.name_en,
                              profile_pic = emp.profile_pic,
                              emp_position = emp.emp_position,
                              department = emp.department,
                              role_emp = perm.role_emp,
                              Modify_date = perm.Modify_date,
                              status_active = emp.status_active,
                              ID_permis = perm.ID_permis,
                          }).ToList();

            var model = new PermisViewModel
            {
                Employees = QSMS,
                Apermis = Permis
            };

            return View(model);
        }

        //--- Add data
        public IActionResult _AddPer(string empid, string level)
        {
            try
            {
                var permis = _context.Permission.Where(t => t.employee_id == empid).FirstOrDefault();
                if (permis != null)
                {
                    return Json(false);
                }
                else
                {
                    var permis_add = new PermissionModel
                    {
                        employee_id = empid,
                        role_emp = level,
                        Modify_date= DateTime.Now,
                    };

                    _context.Permission.Add(permis_add);
                    _context.SaveChanges();

                    return Json(true);

                }

            }
            catch (Exception ex)
            {
                writeEventLog(ex.Message);
                return Json(false);

            }
        }

        //--- SHOW DATA EDIT
        public IActionResult _ShowEdit(int editid)
        {
            try
            {
                var admin = _context.Permission.FirstOrDefault(a => a.ID_permis == editid);

                if (admin != null)
                {
                    var data = new
                    {
                        Perid = admin.ID_permis,
                        levels = admin.role_emp
                    };

                    return Json(data);
                }
                return Json(null);
            }
            catch (Exception ex)
            {
                writeEventLog(ex.Message);
                return Json(false);
            }
        }


        //--- EDIT Admin
        public IActionResult _EditPer(int ePerid, string elevels)
        {
            try
            {
                if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

                if (ePerid == 0 || elevels == null)
                {
                    return Json(false);
                }

                var admin = _context.Permission.FirstOrDefault(a => a.ID_permis == ePerid);
                if (admin.employee_id == ViewData["employee_id"] as string)
                {
                    return Json(false);
                }

                DateTime DateNow = DateTime.Now;
                if (admin != null)
                {
                    admin.role_emp = elevels;
                    admin.Modify_date = DateNow;

                    _context.SaveChanges();
                    return Json(true);
                }
                else
                {
                    return Json(false);
                }
            }
            catch (Exception ex)
            {
                writeEventLog(ex.Message);
                return Json(false);
            }
        }

        //--- DELETE Admin 
        public IActionResult _Delete(int id)
        {
            try
            {
                if (SetLoginNameInViewData()) return RedirectToAction("Error", "Home");

                var admin = _context.Permission.SingleOrDefault(p => p.ID_permis == id);
                if (admin != null)
                {
                    if (admin.employee_id == ViewData["employee_id"] as string)
                    {
                        return Json(false);
                    }
                    else
                    {
                        _context.Permission.Remove(admin);
                        
                        _context.SaveChanges();
                        return Json(true);
                    }
                }
                else
                {
                    return Json(false);
                }
            }
            catch (Exception ex)
            {
                writeEventLog(ex.Message);
                return Json(false);
            }

        }

    }
}

DOS_PPE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DOS_PPE</title>
    <link rel="icon" type="image/.png" href="https://omnia.dexon-technology.com/File/Image/favicon.ico" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/template.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DOS_PPE.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<style>
    #ontop {
        display: none;
    }
</style>
<body class="m-0">
    @{
        var showNavbar = true; // ตั้งค่าเริ่มต้นว่าต้องการแสดง Navbar
        var HideNavbar = ViewData["HideNavbar"];

        if (HideNavbar != null && bool.TryParse(HideNavbar.ToString(), out bool hideNavbarValue))
        {
            showNavbar = false; // ถ้ามีข้อมูล ViewData["HideNavbar"] เป็น true กำหนดให้ไม่แสดง Navbar
        }
    }

    @if (showNavbar)
    {
        <div class="wrapper">
            <!-- Sidebar  -->
            <nav id="sidebar" class="bg-navbar">
                <div class="sidebar-header text-center">
                    <img src="~/image/dos_logo.png" class="logo" />
                </div>

                <!-- Admin -->
                @if (ViewData["admin"] == "admin")
                {
                    <ul class="list-unstyled components">
                        <small class="ps-2 font-black-four">Admin</small>

                        <li class="list @ViewBag.Permission">
                            <a class="nav-link" asp-area="" asp-controller="Permission" asp-action="Permission">
                                <i class="bi bi-person-fill-gear ms-3"></i>
                                <span class="ps-2">Permission</span>
                            </a>
                        </li>
                        <hr />
                    </ul>
                
                }
                <!-- Employee -->
                <ul class="list-unstyled components">
                    @if (ViewData["admin"] == "admin")
                    {
                        <small class="ps-2 font-black-four">Approval</small>
                    }
                    else
                    {
                        <small class="ps-2 font-black-four">Employee</small>
                    }
                    <li class="list @ViewBag.Dashboard">
                        <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Dashboard">
                            <i class="bi bi-bar-chart-line-fill ms-3"></i>
                            <span class="ps-2">Dashboard</span>
                        </a>
                    </li>

                    @if (ViewData["admin"] == "admin")
                    {
                        <li class="list @ViewBag.Approval">
                            <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Index_Approval">
                                <i class="bi bi-check-all ms-3"></i>
                                <span class="ps-2">Approval</span>
                            </a>
                        </li>

                        <li class="list @ViewBag.Receipt">
                            <a class="nav-link" asp-area="" asp-controller="Dashboard" asp-action="Goods_Receipt">
                                <i class="bi bi-database-fill-down ms-3"></i>
                                <span class="ps-2">Goods Receipt</span>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li class="list">
                            <a>
                                <i class="bi bi-calendar3 ms-3"></i>
                                <span class="ps-2">Booking</span>
                            </a>
                        </li>

                        <li class="list">
                            <a>
                                <i class="bi bi-clipboard-plus-fill ms-3"></i>
                                <span class="ps-2">Request</span>
                            </a>
                        </li>
                    }

                  
                    <hr />
                </ul>
               

                <div class="position-absolute width250 bottom-0 start-0 px-4 mb-4 mt-0 text-center">
                    <hr>
                    <span>Personal Protective Equipment</span>
                    <hr>
                </div>
            </nav>

            <div id="content" class="bg-background">
                <nav class="navbar bg-white shadow-sm p-0">
                    <div class="container-fluid">
                        <button type="button" id="sidebarCollapse" class="button-toggle-menu">
                            <i class="bi bi-list fs-3"></i>
                        </button>
                        <ul class="dropdown font-black-two m-0 p-2">
                            <a role="button" data-bs-toggle="dropdown" class="d-flex font-black-two profile">
                                <span class="p-2">
                                    <img src="https://omnia.dexon-technology.com/File/Image/Profile/@ViewData["profile_pic"]" width="32" class="rounded-circle">
                                </span>
                                <span class="d-lg-flex flex-column gap-1 d-none">
                                    <h5 class="fw-bold my-0 fs-6">@ViewData["name_en"]</h5>
                                    <h6 class="my-0 fs-6">@ViewData["employee_id"]</h6>
                                </span>
                            </a>
                            <div class="dropdown-menu bg-white m-0 p-3" id="showpro">
                                <a class="pt-2 pb-2 ps-3 btndrowdownprofile text-decoration-none rounded-3" asp-controller="Home" asp-action="backtohome">
                                    <div class="row">
                                        <div class="col-auto pe-2">
                                            <img src="https://omnia.dexon-technology.com/File/Image/Profile/@ViewData["profile_pic"]" width="60" class="rounded-3">
                                        </div>
                                        <div class="col-auto ">
                                            <p class="text-decoration-none p-0 m-0 fw-bold">@ViewData["name_en"]</p>
                                            <p class="text-decoration-none p-0 m-0">@ViewData["employee_id"]</p>
                                        </div>
                                    </div>


                                </a>
                                <a class="pt-2 pb-2 ps-3 btndrowdownprofile text-decoration-none rounded-3" asp-controller="Home" asp-action="backtohome">
                                    <i class="bi bi-person-fill"></i>
                                    <span class="ps-2 text-decoration-none">My Profile</span>
                                </a>
                                <a class="pt-2 pb-2 ps-3 btndrowdownprofile text-decoration-none rounded-3" asp-controller="Home" asp-action="Logout">
                                    <i class="bi bi-box-arrow-in-right"></i>
                                    <span class="ps-2 text-decoration-none">Sign out</span>
                                </a>
                            </div>

                            <div class="dropdown-menu bg-white m-0 p-0">
                                <a class="pt-2 pb-2 ps-3 btndrowdownprofile text-decoration-none">
                                    <i class="bi bi-person-fill"></i>
                                    <span class="ps-2 text-decoration-none">My Account</span>
                                </a>
                                <a class="pt-2 pb-2 ps-3 btndrowdownprofile text-decoration-none">
                                    <i class="bi bi-box-arrow-in-right"></i>
                                    <span class="ps-2 text-decoration-none">Log out</span>
                                </a>
                            </div>
                        </ul>
                    </div>
                </nav>
                <div class="container-fluid px-4 mt-4 pb-5 mb-5">
                    <main role="main">
                        @RenderBody()
                    </main>
                </div>

                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-12 bottom-0 pb-3 position-absolute">
                                <script>document.write(new Date().getFullYear())</script> © DEXON Technology Public Company Limited
                            </div>
                        </div>
                    </div>
                </footer>
                <a class="rounded-circle btn bg-blue-three  position-fixed bottom-0 end-0 me-4 me-lg-7 mb-5 zindextop" role="button" id="ontop" onclick="window.scrollTo(0, 0);">
                    <i class="bi bi-caret-up-fill"></i>
                </a>
            </div>
        </div>
    }
    else
    {
        <div class="container-fluid m-0 p-0">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    }
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.7.1/dist/chart.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });

            $('.dd-btn').on('click', function () {
                $('.list').removeClass('active');
                $(this).toggleClass('active');
                var ddbtn = $(this).next('.dd-list');
                var icon = $(this).find('i');
                if (ddbtn.is(':visible')) {
                    ddbtn.hide();
                    icon.removeClass('bi-chevron-up').addClass('bi-chevron-down');
                } else {
                    ddbtn.show();
                    icon.removeClass('bi-chevron-down').addClass('bi-chevron-up');
                }
            });

            $('.dd-btn.active').each(function () {
                var icon = $(this).find('i');
                icon.removeClass('bi-chevron-down').addClass('bi-chevron-up');
            });

            $(window).scroll(function () {
                if ($(this).scrollTop() === 0) {

                    $('#ontop').hide();

                } else {

                    $('#ontop').show();

                }

            });
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>